export const useCommonChartOptions = () => ({
  title: String,
  titleFontSize: String,
  tooltipFontSize: String,
  font: String,
  fillStyle: String,
  fillWeight: Number,
  roughness: Number,
  bowing: Number,
  simplification: Number,
  interactive: { type: Boolean, default: true },
  width: Number,
  height: Number,
  margin: Object,
})
